/**
 * Beatcord engine — the shared, platform-neutral audio core extracted from the
 * Discord bot. yt-dlp sourcing, the beatmatching mixer, beat/key/tempo analysis,
 * stems, TTS/STT, lyrics and the ffmpeg PCM pipeline. No Discord, no HTTP here:
 * the bot wraps this for Discord voice, the server wraps it for HTTP/WS/HLS.
 *
 * Re-exported with explicit member lists where flat names are unambiguous, and as
 * namespaces where modules share generic names (FFT_SIZE, interfaces, etc.).
 */

export * from "./active-beat-mesh-v2";
export * from "./adaptive-beat-mesh";
// ── Analysis (DSP) ──
export * from "./adaptive-stretch";
export * from "./affect-intelligence";
export * from "./album-integrity";
export * from "./analysis-cache";
export * from "./analysis-policy";
export * from "./analyzer-transition-knowledge";
export * from "./architecture-status";
export * from "./artist-analytics-transparency";
export * from "./artist-ecosystem-governance";
export * from "./artist-ecosystem-intelligence";
export * from "./audio-fidelity-suite-v4";
export * from "./audio-integrity-qoe-v1";
export * from "./audio-quality-report";
export * from "./audio-source-resolution-policy";
export * from "./backtiming";
export * as beatMath from "./beat-math";
export * from "./beat-mesh-torture-lab-v1";
export * from "./beat-mesh-validation-v3";
export * as beatgrid from "./beatgrid";
export * from "./beatgrid-intelligence-v2";
export * from "./business-validation-governance";
export * as cache from "./cache";
export * from "./capability-selection";
export * from "./causal-decision-confidence-v3";
export * from "./causal-taste-firewall";
export * from "./chart-intelligence";
export * from "./club-performance-validation";
export * from "./club-transition-planner-v2";
export * from "./community-priorities";
export * from "./compute-budget";
export * from "./confidence-fusion";
export type { EngineConfig } from "./config";
// ── Foundation ──
export { config, engineSchema, loadEngineConfig } from "./config";
export * from "./constants";
export * from "./context-serendipity-trust";
export * from "./conversational-director";
export * from "./cross-provider-identity";
export * from "./crowd-experience-v2";
export * from "./crowd-intent-contract";
export * from "./crowd-taste";
export * from "./cultural-genre-trends";
export * from "./deadline-transport-runtime-v2";
export * from "./director-policy";
export * from "./director-soak-v1";
export * from "./distributed-agent-recovery";
export * from "./dsp-precision-gapless-policy";
export * from "./dynamic-beatgrid";
export * from "./ecosystem-milestones";
export * from "./emergency-continuity";
export * as eq from "./eq";
export * from "./evaluation-reliability-v2";
export * from "./evidence-sequencing";
export * from "./experience-engine";
export * from "./experience-event-integration";
export * from "./experience-orchestration";
export * from "./experience-qoe-governance";
export * from "./exploration-uncertainty-teaching";
export * from "./exposure-context-intelligence";
export * from "./familiarity-balance";
export * from "./feedback-attribution";
export * from "./fidelity-spatial-director-v1";
export * as genre from "./genre";
export * from "./genre-signal";
export * from "./golden-mix-benchmark";
export * from "./groove-crowd-intelligence";
export * from "./group-recommendation";
export * from "./hierarchical-stem-perceptual-mixing";
export * from "./human-benchmark-v1";
export * from "./human-intervention-lab-v1";
export * from "./hybrid-recommendation";
export * from "./immersive-rendering-v1";
export * from "./integration-sdk-accessibility-search";
export * from "./journey-intelligence";
export * from "./journey-templates";
export * as key from "./key";
export { detectKeyEssentia } from "./key-essentia";
export * from "./latency-aware-planning";
export type { Logger } from "./logger";
export { c, createLogger, logger } from "./logger";
export * from "./longitudinal-taste-lab-v1";
export * from "./loopability";
export * as loudness from "./loudness";
// ── Metadata / lyrics / cache ──
export * from "./lyrics";
export { masteringFilters } from "./mastering";
export * from "./milestone-readiness";
export * from "./mirror";
export * from "./mix-regions";
export * from "./mixed-playlist-rights";
// ── Mixing / beatmatching ──
export * from "./mixer";
export * from "./mixStation";
export * from "./mobility-karaoke-memory";
export * from "./moment-compute-intelligence";
export * from "./multi-task-analysis";
export * from "./multisensory-attention-experience";
export * from "./music-director";
export * from "./music-knowledge";
export * from "./musical-compiler-deadline-risk";
export * from "./musical-tension";
export * from "./musical-timeline";
export type { NarratorConfig } from "./narrator";
export { DjNarrator } from "./narrator";
export * as narratorPhrases from "./narrator-phrases";
export * from "./offline-audio-validator";
export * from "./offline-director";
export * from "./offline-renderer";
// ── PCM pipeline + format constants ──
export * from "./pcm";
export * from "./perceptual-evaluation";
export * from "./perceptual-masking";
export * from "./perceptual-performance-policy";
export * from "./perceptual-playback-embodiment";
export * from "./performance-stability-v1";
export * from "./performance-style";
export * from "./phrase-cues";
export * from "./platform-evidence-realtime-v1";
export * from "./platform-search-sync-resilience";
export * from "./playback-twin-causal-ledger-v2";
export * from "./presentation-transport-compiler-v1";
export * from "./product-architecture-strategy";
export * from "./progressive-planning";
export * from "./provenance-signal-integrity";
export * from "./provider-innovation-validation";
export * from "./psychoacoustic-transition-critic";
export * from "./quality-guardian";
export * from "./quality-guardian-v3";
export * from "./quality-of-experience";
export * from "./realtime-audio-reliability";
export * from "./realtime-dsp-route-v3";
export * from "./recommendation-intelligence";
export * from "./recommendation-routing-v2";
export * from "./research-experience-policy";
export * from "./research-landscape";
export * from "./research-principles";
export * from "./research-registry";
export * from "./responsible-recommendation";
export * from "./robust-transition-funnel";
export * from "./runtime-evidence-ledger-v1";
export * from "./safe-listening-accessibility";
export * from "./section-importance";
export * from "./semantic-listening-v1";
export * from "./semantic-music-intelligence";
export * from "./session-continuity-platform";
export * from "./session-fatigue";
export * from "./session-journey";
export * from "./social-privacy-journey-ux";
export * from "./social-session-governance";
export * as spectral from "./spectral";
export * from "./stem-compute-provenance-v2";
export * from "./stem-quality";
export * from "./stem-restoration-sequential";
export * from "./stem-transition-utility-v1";
// ── Stems / voice / narration ──
export * as stems from "./stems";
export * from "./strategy-fatigue";
export * from "./structural-dependencies";
export * as stt from "./stt";
export * from "./surprise-budget";
export * from "./taste-dynamics";
export * from "./taste-privacy-governance";
export * as tempo from "./tempo";
export * from "./tempo-awareness";
export * from "./temporal-agent-orchestration";
export * from "./temporal-recommendation-research";
export * from "./track-compatibility";
export * from "./track-identity";
export * from "./track-profile";
export * from "./trackmeta";
export * from "./transform-fidelity-ledger-v2";
export * from "./transition-analyzer";
export * from "./transition-candidates";
export * from "./transition-critic-v2";
export * from "./transition-lifecycle";
export * from "./transition-material-intelligence";
export * from "./transition-override";
export * from "./transition-planner";
export * from "./transition-preview";
export * from "./transition-telemetry";
export * from "./transition-validation-lab-v4";
export * as tts from "./tts";
export * from "./ultimate-vision";
export * from "./validated-experience-innovations";
export * from "./validation-runtime-compiler-v1";
export * from "./vocal-activity";
export * from "./vocal-conflict";
export * as voiceCommands from "./voice-commands";
// ── Sourcing (yt-dlp + Spotify/Apple mirror) ──
export * from "./ytdlp";
